### ISSUE TITLE
[Bug 🐞]: AMP and TUFX incompatability/NRE

### ISSUE THREAD

**Issue by caipi-** [zer0Kerbal/AdjustableModPanel#30]
### Brief description of your issue

Using AMP/KAMP with TUFX and trying to hide the TUFX button breaks AMP functionality

### Steps to reproduce

Install AMP, Install TUFX, try hiding other buttons first, it works. Try hiding TUFX, nothing vanishes and a NRE is logged, afterwards I cannot hide or show anything anymore - even buttons that I could previously hide/show. The buttons are essentially locked and do not react to AMP anymore.

### Expected behavior

No NRE and AMP should be able to hide/show any app launcher button just like before trying to hide TUFX, including TUFX.

### Actual behavior

The game still works, but AMP lost its functionality in all scenes. A scene change (e.g. KSP -> VAB/SPH) does not help. There is a NRE with every scene change.

### Environment

```shell
Mod: AMP 1.5.5 & TUFX 1.0.2.3
KSP: 1.12.3
Download/Installation: AMP: manual download and installation from Curseforge, currently latest version 1.5.5 ( https://www.curseforge.com/kerbal/ksp-mods/AdjustableModPanel ) & TUFX: manual download and installation from GitHub, latest version 1.0.2.3 ( https://github.com/shadowmage45/TUFX/releases )
KSP.log: https://www.dropbox.com/s/sb8jbdy8uqtbl9r/KSP.log?dl=0
Player.log: https://www.dropbox.com/s/hlg4rjjanngudoo/Player.log?dl=0
```

### How did you download and install this?

CurseForge (download and manual installation)

**Comment by zer0Kerbal** [comment]
@caipi- thank you for the 🐛 report.

Would you kindly try the below version and tell me if the issue still exists with it. Thank you!

 Most recent version (the one I was about to release). Kindly tell me when you have it downloaded so I can remove the link.
[AdjustableModPanel-1.5.99.0-release-CF.zip](https://github.com/zer0Kerbal/AdjustableModPanel/files/8404984/AdjustableModPanel-1.5.99.0-release-CF.zip)

**Comment by caipi-** [comment]
I have downloaded it, you can remove it. I will try it in a few minutes.

**Comment by caipi-** [comment]
@zer0Kerbal Initial test result in my KSP test environment & my regular heavily modded game: The NRE and issue did not happen with the new version 1.5.99.0. It seems to be fixed.
So I'm just gonna close the issue here for now.

FYI: I also tested if the other mods I have installed created a similar issue. I went through several scenes and removed all buttons. No issue so far. Looks good and stable to me.

_Btw: Please kindly disregard the fact that I accidentally had two ModuleManagers in my test environment in the initial logs. That was an oversight on my part after being happy to have found the reason/mod in my normal game (where only one MM is present, the latest one of course), hastily installing TUFX without realizing it came bundled with the old MM, and uploading the logs without looking at their beginning. -.-'_

**Comment by zer0Kerbal** [comment]
>[](https://github.com/apps/project-bot)@[project-bot](https://github.com/apps/project-bot) project-bot bot moved this from Closed to Needs triage in [Issue/Request Tracker](https://github.com/zer0Kerbal/AdjustableModPanel/projects/3#card-80084028)

*shakes 👊 at project-bot* now you work, you ne'er-do-well rapscallion! Your mother was a twitter-bot!

Thank you @caipi- very much appreciated!

On a side note, that is why I try to not include other .dll's in my releases - too easy to git multiple extras that can, and often do mess things up 🐒 🔧 - like miniAVC.dll.... 

It has happened to all of us - including and especially me. (multiple same .dll's)

Enjoy the early pre-release! You've earned it. 🦅 🧧
